// code_report Solution
// Problem Link (Contest):  https://leetcode.com/contest/weekly-contest-176/problems/count-negative-numbers-in-a-sorted-matrix/
// Problem Link (Practice): https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/
// Video Link:              https://youtu.be/pDbDtGn1PXk

// Note: this was testing using oK, an implementation of K5 (There is K1, 2, 3, 4, 5, 6, 7 and 9)
// https://github.com/JohnEarnest/ok
// http://johnearnest.github.io/ok/index.html (Try oK online)

countNegatives: +//0>
