# code_report Solution
# Problem Link (Contest):  https://leetcode.com/contest/weekly-contest-210/problems/maximum-nesting-depth-of-the-parentheses/
# Problem Link (Practice): https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/

MaxDepth ← ⌈´·+`·-˝"()"=⌜⊢ 

# Tests
MaxDepth "(1+(2*3)+((8)/4))+1" # 3
MaxDepth "(1)+((2))+(((3)))"   # 3
MaxDepth "1+(2*3)/(2-1)"       # 1
MaxDepth "1"                   # 0
