# Problem Link: https://leetcode.com/contest/weekly-contest-274/problems/destroying-asteroids/

# Original (suboptimal solution)
AsteroidsDestroyed ← (⊣+·+´>/⊢)(∧´(¯1↓+`∘∾)≥⊢)(∧≤/⊢)

# Final Solution
AsteroidsDestroyed ← (∧´(+`¯1⊸↓∘∾)≥⊢)⟜∧

# Tests
10 AsteroidsDestroyed 3‿9‿19‿5‿21                # 1
5  AsteroidsDestroyed 4‿9‿23‿4                   # 0 
86 AsteroidsDestroyed 156‿197‿192‿14‿97‿160‿14‿5 # 1
