# Problem Link: https://leetcode.com/contest/weekly-contest-322/problems/circular-sentence

# My original Solution
Split ← (⊢-˜+`×¬)∘=⊔⊢
IsCircularSentence ← {∧´=´˘∘‿2⥊1⌽∾(⊑∾⊑∘⌽)¨' 'Split𝕩}

# Adám Brudzewsky's-Inspired Solution
IsCircularSentence ← {(⊢´¨≡1⌽⊑¨)' 'Split𝕩}

# Tests
IsCircularSentence "leetcode exercises sound delightful" # 1
IsCircularSentence "eetcode"                             # 1
IsCircularSentence "Leetcode is cool"                    # 0 
