# Problem Link: https://leetcode.com/contest/biweekly-contest-61/problems/count-number-of-pairs-with-absolute-difference-k/
# Permalink: https://mlochbaum.github.io/BQN/try.html#code=IyBQcm9ibGVtIExpbms6IGh0dHBzOi8vbGVldGNvZGUuY29tL2NvbnRlc3QvYml3ZWVrbHktY29udGVzdC02MS9wcm9ibGVtcy9jb3VudC1udW1iZXItb2YtcGFpcnMtd2l0aC1hYnNvbHV0ZS1kaWZmZXJlbmNlLWsvCgpDb3VudEtEaWZmZXJlbmNlIOKGkCArwrTiiJjipYriiqM9LeKMnMuc4oiY4oqiCgojIFRlc3RzCjEgQ291bnRLRGlmZmVyZW5jZSAx4oC/MuKAvzLigL8xICAgIyA0CjMgQ291bnRLRGlmZmVyZW5jZSAx4oC/MyAgICAgICAjIDAKMiBDb3VudEtEaWZmZXJlbmNlIDPigL8y4oC/MeKAvzXigL80ICMgMw==

CountKDifference ← +´∘⥊⊣=-⌜˜∘⊢

# Tests
1 CountKDifference 1‿2‿2‿1   # 4
3 CountKDifference 1‿3       # 0
2 CountKDifference 3‿2‿1‿5‿4 # 3
